// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929163705_UpdateRelatorioRelations")]
    partial class UpdateRelatorioRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InformacaoNutricional")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ingredientes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NutriScore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("backend.Models.ProdutoReceita", b =>
                {
                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("integer");

                    b.HasKey("ProdutoId", "ReceitaId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("ProdutosReceitas");
                });

            modelBuilder.Entity("backend.Models.ProdutoSupermercado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Disponibilidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("SupermercadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SupermercadoId");

                    b.ToTable("ProdutosSupermercados");
                });

            modelBuilder.Entity("backend.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instrucoes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Receitas");
                });

            modelBuilder.Entity("backend.Models.Relatorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Relatorios");
                });

            modelBuilder.Entity("backend.Models.RelatorioProduto", b =>
                {
                    b.Property<int>("RelatorioId")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.HasKey("RelatorioId", "ProdutoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("RelatoriosProdutos");
                });

            modelBuilder.Entity("backend.Models.RelatorioReceita", b =>
                {
                    b.Property<int>("RelatorioId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceitaId")
                        .HasColumnType("integer");

                    b.HasKey("RelatorioId", "ReceitaId");

                    b.HasIndex("ReceitaId");

                    b.ToTable("RelatoriosReceitas");
                });

            modelBuilder.Entity("backend.Models.Supermercado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Supermercados");
                });

            modelBuilder.Entity("backend.Models.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("backend.Models.ProdutoReceita", b =>
                {
                    b.HasOne("backend.Models.Produto", "Produto")
                        .WithMany("ProdutosReceitas")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Receita", "Receita")
                        .WithMany("ProdutosReceitas")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("backend.Models.ProdutoSupermercado", b =>
                {
                    b.HasOne("backend.Models.Produto", "Produto")
                        .WithMany("ProdutosSupermercados")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Supermercado", "Supermercado")
                        .WithMany("ProdutosSupermercados")
                        .HasForeignKey("SupermercadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Supermercado");
                });

            modelBuilder.Entity("backend.Models.Relatorio", b =>
                {
                    b.HasOne("backend.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("backend.Models.RelatorioProduto", b =>
                {
                    b.HasOne("backend.Models.Produto", "Produto")
                        .WithMany("RelatoriosProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Relatorio", "Relatorio")
                        .WithMany("RelatoriosProdutos")
                        .HasForeignKey("RelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("backend.Models.RelatorioReceita", b =>
                {
                    b.HasOne("backend.Models.Receita", "Receita")
                        .WithMany("RelatoriosReceitas")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Relatorio", "Relatorio")
                        .WithMany("RelatoriosReceitas")
                        .HasForeignKey("RelatorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receita");

                    b.Navigation("Relatorio");
                });

            modelBuilder.Entity("backend.Models.Produto", b =>
                {
                    b.Navigation("ProdutosReceitas");

                    b.Navigation("ProdutosSupermercados");

                    b.Navigation("RelatoriosProdutos");
                });

            modelBuilder.Entity("backend.Models.Receita", b =>
                {
                    b.Navigation("ProdutosReceitas");

                    b.Navigation("RelatoriosReceitas");
                });

            modelBuilder.Entity("backend.Models.Relatorio", b =>
                {
                    b.Navigation("RelatoriosProdutos");

                    b.Navigation("RelatoriosReceitas");
                });

            modelBuilder.Entity("backend.Models.Supermercado", b =>
                {
                    b.Navigation("ProdutosSupermercados");
                });
#pragma warning restore 612, 618
        }
    }
}
